- openapi/oi.yaml
Open it in swagger new editor to interact correctly, steps:
1. go to https://editor-next.swagger.io/
2. File -> Import URL
3. https://raw.githubusercontent.com/pagopa/oneidentity/feat/openapi/openapi/oi.yaml
Unfortunately this new editor doesn't support load from url directly as it was with the previous one :|
> Add first draft of openapi definition

- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/Client.java
- src/oneid/oneid-ecs-core/pom.xml
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/AccessTokenSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/OIDCSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/RecordType.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/SAMLSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/AttributeDTO.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/AuthorizationRequestDTO.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionService.java
- src/oneid/pom.xml
This **PR** adds interface definition for `service` Package:
- `SAMLService`
- `OIDCService`
- `SessionService`
> feat: Add interfaces definition

- src/oneid/oneid-common/model/pom.xml
- src/oneid/oneid-ecs-core/pom.xml
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/AccessTokenSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/OIDCSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/SAMLSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/Session.java
- src/oneid/oneid-ecs-core/src/main/resources/application.properties
- src/oneid/pom.xml
This **PR** adds `DynamoDB` interaction setup for OI session management.
> feat: setup dynamodb interaction

- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/Client.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnector.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/SessionException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/enums/ErrorCode.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/producers/ClientProducer.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/SAMLUtils.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
This PR adds:
- `saveSession` implementation for `SessionService`
- Some `TODOs` resolved
> Feat: OI-142 implementare il metodo save session per saml in session service

- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
This PR will add a refactor of the method saveSession to improve readability and avoid redundancy
> Refactor: add saveItem to reduce redundancy of code

- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/AccessTokenSession.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/TokenDataDTO.java
This PR adds support for `oidc/token` route
> feat: setup oidc/token controller

- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SAMLUtils.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/config/ConfigBasicParserPool.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/MetadataResolverExtended.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/SAMLUtilsExtendedCore.java
This **PR** will add support for cie with the newly introduced MetadataResolverExtended
> feat: Add cie support using MetadataResolverExtended

- src/oneid/oneid-ecs-core/metadata/spid.xml
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
This PR adds OIDC `/.well-known/openid-configuration` route
> Feat: OIDC provider metadata

- openapi/oi.json
- openapi/oi.yaml
- src/infra/dev/api/oi.tpl.json
- keep original openapi definition in sync
> feat: .well-known/openid-configuration route definition

- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/KMSConnector.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/KMSConnectorImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/JWKSSetDTO.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/JWKSUriMetadataDTO.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/OIDCUtils.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
This **PR** adds `/oidc/keys` route
> Feat: OIDC keys route

- src/infra/dev/api/oi.tpl.json
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
This **PR** adds `saml/assertion` route
> Feat: add saml controller assertion route

- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
This **PR** will put validation of SAMLResponse signature after saving it
> fix: Save SAMLResponse before validation

- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SAMLUtils.java
- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SAMLUtilsConstants.java
- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/config/ConfigBasicParserPool.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/SAMLUtilsExtendedCore.java
- src/oneid/oneid-lambda-service-metadata/src/main/java/it/pagopa/oneid/SAMLUtilsExtendedMetadata.java
- src/oneid/oneid-lambda-service-metadata/src/main/java/it/pagopa/oneid/ServiceMetadata.java
This **PR** will add the following changes:
- Add correct contactType and Municipality
- Remove static references to samlUtils for both lambda-service-metadata and ecs-core
> fix: Add correct fields for cie metadata

- src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnectorImpl.java
- src/oneid/oneid-common/connector/src/main/resources/application.yaml
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/enums/AuthLevel.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/enums/converter/AuthLevelConverter.java
- src/oneid/oneid-common/model/src/main/resources/application.yaml
- src/oneid/oneid-common/utils/src/main/resources/application.yaml
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/GenericHTMLException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/MetadataResolverExtended.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/SAMLUtilsExtendedCore.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OneIDController.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
- src/oneid/oneid-ecs-core/src/main/resources/application.properties
- src/oneid/oneid-lambda-client-registration/src/main/resources/application.properties
This **PR** updates log format:
~```%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n```~
```%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) [%C.%M] %s%e%n```
> chore: update log standard

- src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnector.java
- src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnectorImpl.java
- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/HASHUtils.java
This **PR** implements connector layer of ClientRegistration resource
> Feat: client registration connector

- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/Client.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/ClientExtended.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/exception/enums/ErrorCode.java
- src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/HASHUtils.java
- src/oneid/oneid-ecs-core/pom.xml
- src/oneid/oneid-lambda-client-registration/pom.xml
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/ClientRegistrationServiceException.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/ClientUtilsException.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/ErrorResponse.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientMetadataDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientRegistrationRequestDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientRegistrationResponseDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationService.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationServiceImpl.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/utils/ClientConstants.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/utils/ClientUtils.java
This **PR** adds:
- a method to save Client's information in connector layer;
-  some changes to Client's related objects;
-  ClientRegistration's Service layer method (saveClient);
-  basic Exception handling features.
> Feat: client registration service save

- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/InvalidRedirectURIException.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientMetadataDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientRegistrationResponseDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/enums/ClientRegistrationErrorCode.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationServiceImpl.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/web/controller/ClientRegistrationController.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/web/dto/ClientRegistrationErrorDTO.java
This **PR** completes the Dynamic Client Registration flow
> Feat: client registration service controller

- src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnector.java
- src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnectorImpl.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/exception/AuthorizationErrorException.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/exception/ClientNotFoundException.java
- src/oneid/oneid-lambda-client-registration/pom.xml
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/InvalidLogoURIException.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/InvalidRedirectURIException.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientMetadataDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationService.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationServiceImpl.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/utils/ClientUtils.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/utils/CustomURIUtils.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/web/controller/ClientRegistrationController.java
This **PR** will introduce the route to get client metadata.
Also added a fix for parameters of /register POST
> feat: Add OIDC Client Configuration Endpoint

- openapi/oi.json
- openapi/oi.yaml
- src/infra/dev/api/oi.tpl.json
fix: /oidc/register api definition
feat: /oidc/register/client_id api definition
> API: /oidc/register api definition

- .gitignore
- src/oneid/oneid-common/connector/pom.xml
- src/oneid/oneid-common/connector/src/test/java/it/pagopa/oneid/common/connector/ClientConnectorImplTest.java
- src/oneid/oneid-common/connector/src/test/resources/application.properties
This **PR** adds tests for the class ClientConnectorImpl.
> Test: ClientConnectorImpl

- src/oneid/oneid-common/model/pom.xml
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/exception/AuthorizationErrorException.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/exception/ClientNotFoundException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/IDPNotFoundException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/InvalidScopeException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/UnsupportedResponseTypeException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/exception/mapper/ExceptionMapperTest.java
This **PR**:
- adds tests for ExceptionMapper;
- Updates the the exceptions related to OAuth2 errors.
> Test: ecs core exception mapper

- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/SAMLControllerTest.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/mock/MockSAMLControllerSessionServiceImpl.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/mock/SAMLControllerTestProfile.java
This **PR** adds `SAMLController` unit tests.
> Test: add SAMLController tests

- .github/workflows/code-review.yml
- src/oneid/pom.xml
This **PR** adds SonarCloud to the repo
> Test: SonarCloud

- src/oneid/oneid-ecs-core/metadata/cie.xml
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/MetadataResolverExtended.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/SAMLUtilsExtendedCore.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
This PR adds CIE pre-production environment support
> feat: add pre-prod cie support

- src/infra/uat/eu-south-1/variables.tf
The image version is the current running image version.
> feat: Update uat ecs image

- src/oneid/oneid-lambda-client-registration/pom.xml
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientMetadataDTO.java
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientRegistrationRequestDTO.java
- src/oneid/oneid-lambda-client-registration/src/test/java/it/pagopa/oneid/service/ClientRegistrationServiceImplTest.java
- src/oneid/oneid-lambda-client-registration/src/test/java/it/pagopa/oneid/service/utils/CustomURIUtilsTest.java
- src/oneid/oneid-lambda-client-registration/src/test/java/it/pagopa/oneid/web/controller/ClientRegistrationControllerTest.java
This **PR** adds tests for client-registration module
> Test: client registration

- src/oneid/oneid-lambda-is-gh-integration/pom.xml
- src/oneid/oneid-lambda-is-gh-integration/src/main/java/it/pagopa/oneid/connector/GitHubConnectorImpl.java
- src/oneid/oneid-lambda-is-gh-integration/src/main/java/it/pagopa/oneid/connector/RepositoryConfig.java
- src/oneid/oneid-lambda-is-gh-integration/src/main/java/it/pagopa/oneid/service/GitHubServiceImpl.java
- src/oneid/oneid-lambda-is-gh-integration/src/main/java/it/pagopa/oneid/web/ISGHIntegration.java
- src/oneid/oneid-lambda-is-gh-integration/src/test/java/it/pagopa/oneid/connector/GitHubConnectorImplTest.java
- src/oneid/oneid-lambda-is-gh-integration/src/test/java/it/pagopa/oneid/service/GitHubServiceImplTest.java
- src/oneid/oneid-lambda-is-gh-integration/src/test/java/it/pagopa/oneid/service/ISServiceImplTest.java
- src/oneid/oneid-lambda-is-gh-integration/src/test/java/it/pagopa/oneid/web/ISGHIntegrationTest.java
Added unit tests for `is-gh-integration` lambda and a refactoring of `GitHubConnectorConnectorImpl` code that was needed for testing
> test: Add unit tests for is-gh-integration lambda

- src/oneid/oneid-ecs-core/src/main/webui/src/components/EndingPage.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/hooks/useLoginError.test.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/hooks/useLoginError.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/de.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/en.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/fr.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/it.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/sl.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/Login.test.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/Login.tsx
- removes unused strings from langMap objects
- updates missing translations in locales
- removes explicit breaks in strings using a styling approach instead
- refactoring of terms and conditions localization rendering
- removes unused productId2ProductTitle function
- unit tests
> feat: [OI-214] i18n locale updates and refactoring

- src/oneid/oneid-ecs-core/src/main/resources/application.properties
- switch build directory to dist, after vite migration
> Use quinoa only in local development

- src/oneid/oneid-ecs-core/src/main/webui/src/components/ImageFallback.test.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/components/ImageFallback.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/Login.tsx
- fixes client logo style
- refactors ImageWithFallback to handle multiple cases
- unit tests
> fix: [OI-276] client logo style

- src/oneid/oneid-ecs-core/src/main/webui/src/locale/de.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/en.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/fr.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/it.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/locale/sl.ts
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/SpidModal.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/SpidSelect.tsx
- adds a placeholder in case no idp is found
- localization strings updated
- refactoring
> feat: [OI-227] no idps placeholder

- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/Login.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/SpidSelect.tsx
- src/oneid/oneid-ecs-core/src/main/webui/src/utils/constants.ts
- removes empty redirect button from login page
- removes redirect button (close icon) from spid select
- removes ENABLE_LANDING_REDIRECT constant
> fix: [OI-278] removes redirect buttons

- .github/workflows/deploy-oneid-core.yml
- src/oneid/oneid-ecs-core/Dockerfile
- src/oneid/oneid-ecs-core/dep-sha256.json
- src/oneid/oneid-ecs-core/pom.xml
- src/oneid/pom.xml
This pr will introduce maven plugin for dependency hashing pinning inside the pipeline.
> ci: Add maven plugin for dependency hashing in the pipeline

- src/oneid/oneid-fe/src/App.tsx
- src/oneid/oneid-fe/src/components/EndingPage.test.tsx
- src/oneid/oneid-fe/src/components/EndingPage.tsx
- src/oneid/oneid-fe/src/hooks/useLoginError.test.tsx
- src/oneid/oneid-fe/src/hooks/useLoginError.tsx
- src/oneid/oneid-fe/src/pages/loginError/LoginError.test.tsx
- src/oneid/oneid-fe/src/pages/loginError/LoginError.tsx
- src/oneid/oneid-fe/src/pages/logout/Logout.tsx
- removes EndingPage second button
- refactors EndingPage
- updates EndingPage usage
- refactors App routing
- sets a generic error on a timeout
- updates unit tests
> feat: [OI-300] EndingPage refactoring

- src/oneid/oneid-fe/src/hooks/useLoginError.tsx
- adds new error codes mapping
- refoctors the useLoginError hook
> feat: [OI-256] error code map

- AUTHORS
- LICENSE
- README.md
- publiccode.yml
This PR adds:
* a proper LICENSE as discussed previously (MPL-2.0);
* Authorship info and relevant copyrights;
* a `publiccode.yml` file for indexing the project in the [Developers Italia](https://developers.italia.it) National Reuse catalog as provided by the law;
* relevant info in the README file.
Please @sebbalex LMKWYT, thanks!
> Add licensing info

- src/oneid/oneid-lambda-update-idp-status/lambda.py
This **PR** adapts the application code to the new CloudWatch Alarm configuration from absolute values (`IDPSuccess`, `IDPError`) to `ErrorRate`.
> feat: change alarm logic

- .github/workflows/deploy-lambda-retrieve-status.yml
- src/oneid/oneid-lambda-retrieve-status/lambda.py
This **PR** adds `oneid-lambda-retrieve-status` code for the `oneid.pagopa.it/{type}/status` endpoint.
> feat: lambda retrieve status

- src/oneid/oneid-fe/src/hooks/useLoginError.tsx
- src/oneid/oneid-fe/src/pages/loginError/LoginError.tsx
- an useCallback circular dependency was causing a deadloop
> Errors text and description did not appear.

- src/infra/dashboards/client_error_widget.tpl.json
- src/infra/dashboards/idp_error_widget.tpl.json
- src/infra/dev/eu-south-1/main.tf
- src/infra/modules/monitoring/README.md
- src/infra/modules/monitoring/locals.tf
- src/infra/modules/monitoring/main.tf
- src/infra/modules/monitoring/variables.tf
- src/infra/prod/eu-central-1/main.tf
- src/infra/prod/eu-south-1/main.tf
- src/infra/uat/eu-south-1/main.tf
- Added templates for both idp and client errors widget
- Added infrastructure needed for the new dashboard
> infra: Add dashboard for detailed client and idp errors

- src/infra/api/oi.tpl.json
This **PR** update the openapi file:
- update /register input and output models
- update /status output model with example
> Feat: openapi update

- src/infra/api/oi.tpl.json
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/ClientService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/ClientServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/SPARouting.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OneIDController.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/ClientServiceImplTest.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/OneIDControllerTest.java
- src/oneid/oneid-fe/.env.dev
- src/oneid/oneid-fe/.env.development
- src/oneid/oneid-fe/.env.prod
- src/oneid/oneid-fe/.env.test
- src/oneid/oneid-fe/.env.uat
- src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/web/controller/ClientRegistrationController.java
- src/oneid/oneid-lambda-client-registration/src/test/java/it/pagopa/oneid/web/controller/ClientRegistrationControllerTest.java
This **PR** introduces the clients route feature to the project. The changes include the following:
- `/clients`: Retrieves all clients information;
- Update some method name of client registration lambda;
- Updated the OpenAPI specification to include the new endpoints and their respective details;
> Feat: clients route

- src/oneid/oneid-common/connector/src/test/java/it/pagopa/oneid/common/connector/ClientConnectorImplTest.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/Client.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/ClientExtended.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/ClientFE.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/converters/HashMapAttributeConverter.java
- src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/converters/LocalizedContentAttributeConverter.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MockClientProducer.java
This **PR** adds some additional fields for the Client:
- String docUri
- String a11yUri
- String cookieUri
- String backButtonEnabled
- Map localizedContent
> Feat:client registration optional fields

- src/infra/uat/eu-south-1/variables.tf
Change CIE IDP endpoint from collaudo to preproduzione
> feat: change cie idp in uat env

- src/oneid/docker_mock/batchDynamo.json
- src/oneid/oneid-fe/index.html
- src/oneid/oneid-fe/src/components/EndingPage.tsx
- src/oneid/oneid-fe/src/pages/login/Login.test.tsx
- src/oneid/oneid-fe/src/pages/login/index.tsx
- src/oneid/oneid-fe/src/pages/loginError/LoginError.tsx
cosmetics: new meta title
style: error pages tailoring
> fix: handling clients api missing fields case

- src/infra/dashboards/client_aggregated_widget.tpl.json
- src/infra/dashboards/client_error_widget.tpl.json
- src/infra/dashboards/idp_error_widget.tpl.json
- src/infra/dev/eu-south-1/locals.tf
- src/infra/prod/eu-central-1/locals.tf
- src/infra/prod/eu-south-1/locals.tf
- src/infra/uat/eu-south-1/locals.tf
- add cie entity id to idps list for each environment
- add live data for detailed metrics dashboard ([source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-live-data.html))
> chore: Add idp cie to detailed metrics dashboard

- src/infra/dashboards/user_client_related_error_widget.tpl.json
- src/infra/dashboards/user_idp_related_error_widget.tpl.json
- src/infra/modules/monitoring/README.md
- src/infra/modules/monitoring/locals.tf
- src/infra/modules/monitoring/variables.tf
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/CloudWatchConnector.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/CloudWatchConnectorImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/SAMLResponseStatusException.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLService.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
- src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java
- src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/SAMLControllerTest.java
- Added users related errors metrics 
- Added dashboard widgets to new metrics
> feat: Add user related error metrics

- src/oneid/oneid-fe/package.json
- src/oneid/oneid-fe/src/components/Header.test.tsx
- src/oneid/oneid-fe/src/components/Header.tsx
- src/oneid/oneid-fe/src/pages/login/index.tsx
- src/oneid/oneid-fe/src/services/api.ts
- src/oneid/oneid-fe/yarn.lock
> feat: support multi theme content map for each client

- src/oneid/docker_mock/batchDynamo.json
- src/oneid/oneid-fe/src/components/footer/Footer.tsx
- footer component localized map content reference
- new schema mock db for local testing
> fix: footer component localized map content reference

- src/infra/api/oi-admin.tpl.json
- src/oneid/oneid-lambda-client-manager/index.py
- src/oneid/oneid-lambda-client-manager/requirements-dev.txt
- src/oneid/oneid-lambda-client-manager/test_index.py
This **PR** updates some client-manager api, replacing client_id with user_id
> Feat: update client manager api

- src/infra/api/oi-admin.tpl.json
- src/infra/api/oi.tpl.json
This **PR** updates the client registration and client manager OpenAPI files to allow the AWS Console to display the correct values. These changes ensure more accurate representation and integration with AWS.
> Feat:oi 365 367 update openapi files

- src/infra/api/oi-admin.tpl.json
- src/oneid/oneid-lambda-client-manager/index.py
- fix: check if key username + namespace already exists during update
- fix: update openapi
- fix: convert route for update internal IDP User from PUT to PATCH due to the defined behaviour
- OI-405
- OI-406
- Local tests
- Cloud tests (dev env)
> fix: update internal idp users

- src/infra/api/oi-admin.tpl.json
- src/oneid/oneid-lambda-client-manager/index.py
- src/oneid/oneid-lambda-client-manager/test_index.py
- Paginate `/client-manager/client-users/<user_id>` route to optimize data fetching 
- OI-408
- Local tests
- Cloud tests (dev)
> feat: internal idp paginated get users

- src/config/validator/users.json
- change 1
- change 2
- change 3
- task/story number
- Local tests
> Add Rand to users.json

- src/infra/api/oi-admin.tpl.json
- src/infra/api/oi.tpl.json
Set CSP policy from `report-only` to `blocking` mode
[OI-418]
- Local tests
- Cloud (dev and uat envs)
[OI-418]: https://pagopa.atlassian.net/browse/OI-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: blocking mode csp

- src/infra/api/oi-admin.tpl.json
- added csp url
- removed unused url /dashboard/{clientid+}
- task/story number
- Local tests
> fix: Add csp to support cognito url

- src/infra/dev/eu-south-1/main.tf
- src/infra/modules/sqs/main.tf
- src/infra/modules/sqs/variables.tf
- src/infra/prod/eu-central-1/main.tf
- src/infra/prod/eu-south-1/main.tf
- src/infra/uat/eu-south-1/main.tf
- Alarm on `OIError` with dimension value = `SQSSendMessageFailures` when threshold (1) is crossed
- Alarm on `pdv-reconciler-sqs-dlq` when there are messages available in the queue (it means that one or more retry performed by the async process didn't work)
- OI-514
- Cloud tests
> feat: alarm on sqs message error

- .github/workflows/deploy-lambda-cert-exp-checker.yml
- change 1
- change 2
- change 3
- task/story number
- Local tests
> feat: Deploy lambda cert-exp-checker

- .github/workflows/deploy-lambda-cert-exp-checker.yml
- change 1
- change 2
- change 3
- task/story number
- Local tests
> fix: set correct var name for key
