pagopa/oneidentity

src/oneid/oneid-common/model/pom.xml
src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/Client.java
src/oneid/oneid-ecs-core/Dockerfile
src/oneid/oneid-ecs-core/Dockerfile.native
src/oneid/oneid-ecs-core/pom.xml
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/ClientConnector.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/ClientConnectorImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/CallbackURINotFoundException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/ClientNotFoundException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/GenericAuthnRequestCreationException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/IDPNotFoundException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/SAMLUtilsException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/enums/ErrorCode.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/SAMLSession.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/Session.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/producers/ClientProducer.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLService.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OneIDController.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/AuthorizationRequestDTOExtended.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/TokenRequestDTOExtended.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/utils/WebUtils.java
src/oneid/pom.xml

This PR adds:
- Dockerfile for JVM mode
- `ClientProducer` bean to load Client information at application startup (clientId, callback_uri, acs_index ecc..)
- Custom exception classes for `oidc/authorize` route
[JIRA TICKET](https://pagopa.atlassian.net/browse/OI-131)

Feat: OI-131 definizione rotta authorize in OIDC controller

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnector.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/utils/ConnectorConstants.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/session/SAMLSession.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionService.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SessionServiceImpl.java

This **PR** will introduce the following changes:
- OI-146: Implementation of `findSession` for SAMLSession record
- OI-147: Implementation of `updateSAMLSession` for SAMLSession record
- OI-148: Implementation of `saveSession` for OIDCSession record
- A refactor of `putItem` for SAMLSession record inside `saveSession` method  to make it consistent
- Added logs for the introduced methods

Feat: Add implementations for SessionConnector methods needed for SamlSession

---

src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SAMLUtilsConstants.java
src/oneid/oneid-lambda-service-metadata/src/main/java/it/pagopa/oneid/SAMLUtilsExtendedMetadata.java
src/oneid/oneid-lambda-service-metadata/src/main/java/it/pagopa/oneid/ServiceMetadata.java
src/oneid/oneid-lambda-service-metadata/src/main/java/it/pagopa/oneid/enums/IdType.java

This **PR** introduces support for **CIE**, including a route that returns the metadata for the selected Identity type (**CIE** or **SPID**) depending on the path parameter selected. Also added the `Extensions` for metadata with correct attributes

feat: Add cie support for metadata lambda

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCService.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/OIDCUtils.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/TokenDataDTO.java

This **PR** adds `iat` and `aud` attributes in `IDToken` parameter returned by `oidc/token` POST.
It also sets `sub` with the `SAMLRequestID` of the session to meet [OIDC RFC expectations](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)

Feat: OI 166 aggiunta parametri obbligatori ad id token secondo rfc

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/InvalidClientException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/InvalidGrantException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/InvalidRequestMalformedHeaderAuthorizationException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/UnsupportedGrantTypeException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/TokenRequestErrorDTO.java

This **PR** adds `Token Request` error response mapping to meet [OIDC RFC Spec.](https://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse)

feat: add Token Request Error response mapping to meet OIDC RFC specification

---

src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/ClientConnectorImpl.java
src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/Client.java
src/oneid/oneid-common/model/src/main/java/it/pagopa/oneid/common/model/ClientExtended.java
src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/model/dto/ClientMetadataDTO.java
src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/ClientRegistrationServiceImpl.java
src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/service/utils/ClientUtils.java
src/oneid/oneid-lambda-client-registration/src/main/java/it/pagopa/oneid/web/validator/AuthLevelValidator.java

This **PR** adds the following updates:
- Replacing `List` type with `Set` in Client Registration to ensure uniqueness
- Replace `Optional.of` with `Optional.ofNullable` in ClientConnector to correctly map `Unauthorized request`

Chore: replace List  parameters with Set in Client Registration

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/OIDCController.java

This **PR** adds support for URL Encoding in Basic Authentication Header for POST `oidc/token` endpoint

Fix: add Basic Auth URL Encoding support on POST oidc/token endpoint

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/AuthorizationRequestDTOExtendedGet.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/dto/AuthorizationRequestDTOExtendedPost.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/validator/ConditionalNotBlankValidator.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/validator/annotations/ConditionalNotBlank.java

This **PR** adds custom `ConditionalNotBlank` annotation for `IPAddress ` field in `AuthorizationRequestDTOGET` and `AuthorizationRequestDTOPost` for `/oidc/authorize` endpoint to avoid Constraint Validation when application is running as quarkus dev profile.

chore: add conditional not blank for IPAddress in authorize endpoint

---

.gitignore
src/oneid/oneid-ecs-core/pom.xml
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/connector/SessionConnectorImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/connector/model/DummySession.java
src/oneid/pom.xml

This **PR** adds setup for testing with a local `DynamoDB` _in-memory_ instance to improve Connector Layer test's effectiveness.
Tests to improve `SessionConnectorImpl` coverage are also added.

Test: add dynamodb local instance junit test

---

.github/workflows/deploy-oneid-core.yml
src/oneid/oneid-ecs-core/Dockerfile
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/KMSConnector.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/KMSConnectorImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/utils/OIDCUtils.java
src/oneid/oneid-ecs-core/src/main/resources/application.properties
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/connector/KMSConnectorImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/connector/SessionConnectorImplTest.java
src/oneid/pom.xml

This **PR** adds general setup for `KMSConnector` tests using Quarkus Dev Services (LocalStack _under the hood_) to emulate KMS giving much more effectiveness to the test suite.
`KMSConnectorImpl` tests are also added.
It introduces a small refactoring for the injection of the `KMSKeyID` to improve method testability.

Test: add ecs core connector tests

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MockSessionConnectorImpl.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MyMockyTestProfile.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SessionServiceImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/utils/OIDCUtilsTest.java

This **PR** adds `SessionServiceImpl` unit tests.
It adds some _Mocked_ beans to improve tests effectiveness and correctly separate behaviours between different application's layers.
Minor code refactoring in `SessionConnectorImpl` which includes the definition of parameterless constructor for enabling mocking.

Test: add ecs core SessionServiceImpl tests

---

src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MockClientProducer.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MyMockyTestProfile.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/OIDCServiceImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java

This **PR** adds unit tests to `oneid-ecs-core` Service Layer

Test: improve oneid-ecs-core Service Layer tests coverage

---

src/oneid/oneid-ecs-core/pom.xml
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/OIDCServiceImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java

This **PR** adds tests to `oneid-ecs-core` Service layer.

Test: improve oneid-ecs-core service layer coverage

---

src/oneid/oneid-lambda-update-idp-metadata/src/main/resources/application.properties

This **PR** solves the error `Quarkus BindException: Port(s) already bound: 8081: Address already in use` when running tests.

fix: add quarkus.http.test-port property

---

.gitignore
src/oneid/oneid-ecs-core/src/main/webui/eslint.config.mjs
src/oneid/oneid-ecs-core/src/main/webui/jest.config.js
src/oneid/oneid-ecs-core/src/main/webui/package.json
src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/__tests__/Login.test.tsx
src/oneid/oneid-ecs-core/src/main/webui/src/pages/login/__tests__/SpidSelect.test.tsx
src/oneid/oneid-ecs-core/src/main/webui/src/pages/loginError/__tests__/LoginError.test.tsx
src/oneid/oneid-ecs-core/src/main/webui/src/pages/logout/__tests__/Logout.test.tsx
src/oneid/oneid-ecs-core/src/main/webui/tsconfig.json
src/oneid/oneid-ecs-core/src/main/webui/vitest.config.mts
src/oneid/oneid-ecs-core/src/main/webui/yarn.lock

- adds vitest and related dependencies
- adds dotenv
- vitest config file
- 80% coverage required
- loads env from .env.test.local file
- execute in run (no-watch) and silent mode
- removes jest config and references
- refactored existing tests to use vitest
- updated ts and eslint config
- adds coverage to gitignore
This PR replaces jest with vitest as a testing framework.
vitest is now the supported testing framework [@pagopa-technology-radar](https://pagopa.github.io/technology-radar/tools/vitest.html)
```bash
yarn test
yarn test:coverage
```

feat: [OI-255] porting to vitest

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/producers/XMLObjectProviderProducer.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/OIDCControllerTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/converter/StringToEnumConverterProviderTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/utils/WebUtilsTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/validator/AuthenticationRequestValidatorTest.java

This **PR** improves `oneid-ecs-core` module code coverage.
Small refactoring needed to improve code testability mostly using _Dependency Injection_ pattern.

Test: improve oneid ecs core coverage

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
src/oneid/oneid-ecs-core/src/main/resources/application.properties
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java

This **PR** adds `3s` of tolerance when validating `issueInstant`, `notOnOrAfter` and `notBefore` SAML Properties during `SAMLResponse` validation.
This is needed to resolve possible sync problem between `SP` (OI) and `IDPs` clock.

Fix: add clock skew handling

---

.github/workflows/deploy-lambda-idp-mock.yml

Remove `uat` and `prod` environment from deploy action.
We don't need to deploy this lambda to environments different from `dev.`

chore: remov uat and prod envs from lambda idp mock deploy github action

---

.github/workflows/deploy-lambda-update-idp-status.yml
src/oneid/oneid-lambda-update-idp-status/lambda.py

This **PR** adds code for `oneid-lambda-update-idp-status` and the related Github Action to deploy it.
This lambda is needed to keep track of IDP status according to the CloudWatch Alarms on the IDP errors.
In particular, it is triggered when the alarm `IDPErrorAlarm-{IDP}` related to a specific IDP passes to the state `IN_ALARM`. This action will update the state to "KO" for the specified IDP. 
To keep track of the come-back of the IDP, after this operation, the lambda enables actions (default disabled) for the `IDPSuccessAlarm-{IDP}` which is a trigger for the lambda when its status passes to `IN_ALARM` (meaning that we have had some successful logins in the last datapoint), in this case the lambda will be triggered and will update the status to "OK" and at the end will disable the …

feat: lambda update idp status

---

.github/workflows/deploy-oneid-core.yml

This **PR** updates the `actions/cache` version to 4.2.0.
Please read [this](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down) for further information.

feat: update actions/cache to version 4.2.0 in deploy workflow

---

src/oneid/oneid-fe/package.json
src/oneid/oneid-fe/src/pages/login/components/SpidButton/SpidButton.test.tsx
src/oneid/oneid-fe/tsconfig.json
src/oneid/oneid-fe/yarn.lock

- vitest cannot be bumped to latest due to a bug on SVGs handling, opening issue upstream

Bump vite and vitest

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/SAMLResponseStatusException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/SAMLValidationException.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/exception/mapper/ExceptionMapper.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLService.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/SAMLServiceImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/SAMLController.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/exception/mapper/ExceptionMapperTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/SAMLServiceImplTest.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/web/controller/SAMLControllerTest.java

This **PR** adds `redirectUri` query parameter when redirecting to the `/login/error?` page allowing the FE to correctly redirect the user to the Product callback with a specific error.

feat: return callback uri to fe

---

src/infra/modules/backend/lambda.tf
src/oneid/oneid-lambda-update-status/lambda.py

This **PR** updates `lambda-update-status` infra and code to be compliant with the new CloudWatch custom alarm naming convention

fix: lambda update status permission

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/web/controller/interceptors/ControllerInterceptor.java

This **PR**  adds an error log when retrieving empty session by authorization code.
This message will help us identifying such cases in order to improve debugging.

chore: add error log when retrieving empty session by authorization code

---

src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/CloudWatchConnector.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/CloudWatchConnectorImpl.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/SessionConnectorImpl.java

This **PR** adds retry during OIDC Session retrieving to bypass the eventually read consistency when reading from GSI in DynamoDB.
With this enhancement we want to reduce the `INVALID_GRANT` errors which appears during `/token` endpoint invocations.

feat: add retry on GSI idx when retrieving OIDC Session

---

src/infra/api/oi.tpl.json

This **PR** enhances the `IDToken` OpenAPI definition in order to improve the documentation of the `/oidc/token` route.
In particular it contains the full representation of the `IDToken` with the JWT description including all optional and mandatory fields.

chore: openapi IDToken description

---

src/infra/modules/backend/ecs.tf

This **PR** set the `evaluation_periods` for the `client_error_alarm` threshold to 2 datapoints.
The goal is to reduce alert noise.

feat: set evaluation_periods for client_error_alarm to 2

---

src/infra/api/oi-admin.tpl.json
src/infra/api/oi.tpl.json

This **PR** adds `CSP` for the subsequent routes (temporarily in **report-only:** mode):
OneIdentity:
- `/login`
- `/login/error`
- `/static/{proxy+}`
- `/assets/{proxy+}`
`Content-Security-Policy-Report-Only: default-src 'self'; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.pagopa.it; frame-ancestors 'none';`
Internal IDP:
- `/assets/{proxy+}`
`Content-Security-Policy-Report-Only: default-src 'self'; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.pagopa.it; frame-ancestors 'none';`
- `/dashboard`
- `/dashboard/{clientId+}`
`Content-Security-Policy-Report-Only: default-src 'self'; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: …

feat(OI-418): add csp policy for oneidentity and internal portal (report-only)

---

src/infra/api/oi.tpl.json
src/infra/dev/eu-south-1/main.tf
src/infra/modules/backend/ecs.tf
src/infra/prod/eu-central-1/main.tf
src/infra/prod/eu-south-1/main.tf
src/infra/uat/eu-south-1/main.tf
src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/SSMConnector.java
src/oneid/oneid-common/connector/src/main/java/it/pagopa/oneid/common/connector/SSMConnectorImpl.java
src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SSMConnectorUtils.java
src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SSMConnectorUtilsImpl.java
src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/SSMConnectorUtilsUtilsImpl.java
src/oneid/oneid-common/utils/src/main/java/it/pagopa/oneid/common/utils/config/ConfigBasicX509Credential.java
src/oneid/oneid-ecs-core/dep-sha256.json
src/oneid/oneid-ecs-core/pom.xml
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/connector/PDVApiClient.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/CertifiedField.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/PDVUserUpsertResponseDTO.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/model/dto/SavePDVUserDTO.java
src/oneid/oneid-ecs-core/src/main/java/it/pagopa/oneid/service/OIDCServiceImpl.java
src/oneid/oneid-ecs-core/src/main/resources/application.properties
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/MockClientProducer.java
src/oneid/oneid-ecs-core/src/test/java/it/pagopa/oneid/service/OIDCServiceImplTest.java

- Added PDV integration to retrieve the Product related `namespaced token` of the fiscalNumber' SAMLResponse and update the PDV User Registry with the SPID/CIE obtained data. 
The functionality is activated via a `pairwise` flag onto the Client data registered inside `ClientRegistrations` table (`true` for pairwise enabling, `false `otherwise).
The API Call to PDV is made using the Product PDV API Key which is stored inside a SecureString parameter with the subsequent format for key retrieval: `/pdv/{clientId}`. This ensures the correct namespace assignment in PDV records.
The resulting JWT when pairwise is enabled will contain a `pairwise` claim, i.e.
```
{
"sub": "_9754d2ac2b4e89040fa372d1742eb02e",
"aud": "bxMiPVktuZ5lBNbZYJ3ODosXL57ltrLp7BgyOkw-0v4",
"pairwise": …
```

feat: pdv namespaced token integration
